<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelInformasiUmumPerjanjianPenjual</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>256.0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>BLANJA.com menyediakan layanan sebagai sarana bagi Penjual untuk memasang, memasarkan dan menjual produknya, dan bagi Penjual yang bermaksud untuk menggunakan layanan situs BLANJA.com agar dapat melakukan penjualan atas produk-produk milik Penjual dan/atau yang dikuasai oleh Penjual di situs BLANJA.com atau untuk mendapatkan layanan-layanan lainnya yang disediakan oleh situs BLANJA.com wajib untuk memenuhi syarat-syarat dan ketentuan serta kebijakan sebagaimana ditetapkan oleh BLANJA.com.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BLANJA.com menyediakan layanan sebagai sarana bagi Penjual untuk memasang, memasarkan dan menjual produknya, dan bagi Penjual yang bermaksud untuk menggunakan layanan situs BLANJA.com agar dapat melakukan penjualan atas produk-produk milik Penjual dan/atau yang dikuasai oleh Penjual di situs BLANJA.com atau untuk mendapatkan layanan-layanan lainnya yang disediakan oleh situs BLANJA.com wajib untuk memenuhi syarat-syarat dan ketentuan serta kebijakan sebagaimana ditetapkan oleh BLANJA.com.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BLANJA.com menyediakan layanan sebagai sarana bagi Penjual untuk memasang, memasarkan dan menjual produknya, dan bagi Penjual yang bermaksud untuk menggunakan layanan situs BLANJA.com agar dapat melakukan penjualan atas produk-produk milik Penjual dan/atau yang dikuasai oleh Penjual di situs BLANJA.com atau untuk mendapatkan layanan-layanan lainnya yang disediakan oleh situs BLANJA.com wajib untuk memenuhi syarat-syarat dan ketentuan serta kebijakan sebagaimana ditetapkan oleh BLANJA.com.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>700.0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>24.0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>252.0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeWebView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeStaticText[1]</value>
   </webElementProperties>
</WebElementEntity>
